In [ ]:
from  google.colab import drive
drive.mount('/content/drive')
from datascience import *

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
titanic_df = pd.read_csv("/content/drive/My Drive/Colab Notebooks/titanic_individuals.csv")

Step : 1
Download and read in this CSV fileLinks to an external site. on individual titanic passengers into a dataframe, remove any entries that do not include the age of the person (indicated as “NA” in the file), and keep only the columns PClass, Age, Survived, and Sex. Create a new column SexCode that maps to the Sex column (1 for "female" and 0 for "male"). Name the data frame as titanic_df.

In [ ]:
titanic_df = titanic_df.dropna(subset=['Age'])
titanic_df = titanic_df[['PClass', 'Age', 'Survived', 'Sex']]
titanic_df['SexCode'] = titanic_df['Sex'].map({'female': 1, 'male': 0})
print(titanic_df.head())

  PClass    Age  Survived     Sex  SexCode
0    1st  29.00         1  female        1
1    1st   2.00         0  female        1
2    1st  30.00         0    male        0
3    1st  25.00         0  female        1
4    1st   0.92         1    male        0

Step : 2 Now use titanic_df to calculate the percent that survived in each subgroup below. Make a grouped bar plot (either stacked or side-by-side) to show the percent that survived for male and the percent that survived for female in the first, second, and third classes. Be sure to include titles, legends and appropriate labels sufficiently sized for readability. (Note: If you couldn't solve Step 1, download and read in this CSV fileLinks to an external site. and start with Step 2.)

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

titanic_df = pd.read_csv("/content/drive/My Drive/Colab Notebooks/step2_titanic_df.csv")
titanic_df = titanic_df.dropna(subset=['Age'])
titanic_df = titanic_df[['PClass', 'Age', 'Survived', 'SexCode']]

survival_rates = titanic_df.groupby(['SexCode','PClass'])['Survived'].mean() * 100
survival_rates

# survival_rates.unstack().plot(kind='bar', stacked=True)
# plt.title('Survival Rates by Passenger Class and Gender')
# plt.xlabel('Passenger Class')
# plt.ylabel('Survival Rate (%)')
# plt.xticks(rotation=0)
# plt.legend(['Female', 'Male'], title='Sex', loc='upper left')
# plt.show()

SexCode  PClass
0        1st       34.400000
         2nd       16.535433
         3rd       14.814815
1        1st       95.049505
         2nd       88.235294
         3rd       45.098039
Name: Survived, dtype: float64

Step : 3 Step 3: Now, only using the following training_data and training_target data sets, create a survival classifier given someone’s class, age, and sex. Use a kNN classifier with k=1, then apply it to a simple test case of your choosing.

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

training_data = [[1, 29, 1],
                 [2, 29, 0],
                 [3, 36, 1],
                 [1, 47, 0],
                 [2, 38, 1],
                 [3, 19, 1],
                 [1, 71, 0],
                 [2, 45, 0],
                 [3, 30, 1]]
training_target = [1, 0, 1, 1, 0, 1, 0, 0, 1]

knn = KNeighborsClassifier(n_neighbors=1)

knn.fit(training_data, training_target)

test_data = [[2, 25, 0]]

prediction = knn.predict(test_data)

print("Predicted survival outcome for test data:", prediction)

if(prediction == 0):
  print("dead")
else:
  print("survived")

Predicted survival outcome for test data: [0]
dead

Step : 4 Now create and print a test_data array with the following cases from first to last in this order.

In [ ]:
test_data = [[1, 4, 0], [1, 90, 0], [2, 43, 1], [2, 40, 0], [3, 17, 1], [3, 29, 0]]
predictions = knn.predict(test_data)
for i in range(len(test_data)):
    if predictions[i] == 1:
        print(f"Case {i+1}: {test_data[i]} - Predicted to survive")
    else:
        print(f"Case {i+1}: {test_data[i]} - Predicted to not survive")

Case 1: [1, 4, 0] - Predicted to survive
Case 2: [1, 90, 0] - Predicted to not survive
Case 3: [2, 43, 1] - Predicted to not survive
Case 4: [2, 40, 0] - Predicted to not survive
Case 5: [3, 17, 1] - Predicted to survive
Case 6: [3, 29, 0] - Predicted to not survive

Step : 5 Make your own training_data and training_target data sets FROM THE REAL DATA in the titanic_df data frame.

In [ ]:
training_data = [  [1, 22, 0],
  [3, 45, 1],
  [2, 32, 0],
  [1, 38, 1],
  [3, 27, 0],
  [2, 29, 1],
  [1, 56, 1],
  [3, 18, 0],
  [2, 21, 0],
  [3, 35, 1]
]

training_target = [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]

Step : 6 Now build a kNN classifier using training_data and training_target data sets from Step 5. Use k=2. Apply that classifier to the test_data array created in Step 4, and briefly discuss the results.

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=2)
knn.fit(training_data, training_target)

predictions = knn.predict(test_data)

for i in range(len(test_data)):
    if predictions[i] == 1:
        print(f"Test case {i+1}: predicted to survive")
    else:
        print(f"Test case {i+1}: predicted to not survive")

Test case 1: predicted to not survive
Test case 2: predicted to not survive
Test case 3: predicted to not survive
Test case 4: predicted to not survive
Test case 5: predicted to not survive
Test case 6: predicted to not survive